# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/temp/DDVHD_Final_project/.Xil/Vivado-8724-elclas032/incrSyn
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/temp/DDVHD_Final_project/Final_project.cache/wt [current_project]
set_property parent.project_path C:/temp/DDVHD_Final_project/Final_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo c:/temp/DDVHD_Final_project/Final_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  //userfs/nl862/w2k/Downloads/DigEng.vhd
  C:/temp/DDVHD_Final_project/Final_project.srcs/sources_1/imports/Downloads/DigEng.vhd
  C:/temp/DDVHD_Final_project/Final_project.srcs/sources_1/new/ACC.vhd
  C:/temp/DDVHD_Final_project/Final_project.srcs/sources_1/imports/Downloads/Param_Counter.vhd
  C:/temp/DDVHD_Final_project/Final_project.srcs/sources_1/imports/Desktop/Control_logic.vhd
  C:/temp/DDVHD_Final_project/Final_project.srcs/sources_1/imports/new/asynchronous_read_ROM.vhd
  C:/temp/DDVHD_Final_project/Final_project.srcs/sources_1/new/asynchronous_read_ROMB.vhd
  C:/temp/DDVHD_Final_project/Final_project.srcs/sources_1/imports/Lab3b-VHDL/RAM.vhd
  C:/temp/DDVHD_Final_project/Final_project.srcs/sources_1/new/MACC.vhd
  C:/temp/DDVHD_Final_project/Final_project.srcs/sources_1/new/Datapath.vhd
  C:/temp/DDVHD_Final_project/Final_project.srcs/sources_1/imports/Lab3b-VHDL/Debouncer.vhd
  C:/temp/DDVHD_Final_project/Final_project.srcs/sources_1/new/Top_level.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top Top_level -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_level_utilization_synth.rpt -pb Top_level_utilization_synth.pb"
